#image: docker:19.03.12
#services:
#  - docker:19.03.12-dind 
  #This allows us to use docker commands
default:
  image: node:14

stages:
- test
test:
 tags: 
    - other-runner

 stage: test
 script: 
     - node -v
     - ls
     - ll
     - cf --version
