include: $CORE_TEMPLATE
variables:
  PROJECT: "docs"
  SPACE: "devops"
deploy:
  extends: .cf_deploy
  only:
    - master
  environment:
      name: development
      url: https://$PROJECT.$DEV_BASE_DOMAIN




