image: docker
services:
    - docker:dind # This allows us to use docker commands
stages:
- test

test:
 tags: 
    - other-runner
 image: node:14
 stage: test
 script: 
     - node -v
     - ls
     - ll
     - cf --version
