include: "https://${CI_SERVER_HOST}/public-resources/gitlab-ci/-/raw/master/templates/build.yaml"
variables:
  PROJECT: "docs"
  SPACE: "devops"
deploy:
  extends: .cf_deploy
  only:
    - master
  environment:
      name: development
      url: https://$PROJECT.$DEV_BASE_DOMAIN
