include: "https://gitlab.orderhive.plus/public-resources/gitlab-ci/-/raw/master/templates/build.yaml"
variables:
  PROJECT: "docs"
deploy:
  extends: .cf_deploy
  variables:
      SPACE: "devops"
  only:
    - master
  environment:
      name: development
      url: https://$PROJECT.$DEV_BASE_DOMAIN
